<a href="https://colab.research.google.com/github/Chandini-M555/Data_Science_Task/blob/main/Data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Data cleaning: It is a process of removing data by extracting only wanted data
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv",encoding="ISO-8859-1")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ano       6454 non-null   int64
 1   mes       6454 non-null   object
 2   estado    6454 non-null   object
 3   numero    6322 non-null   object
 4   encontro  6454 non-null   object
dtypes: int64(1), object(4)
memory usage: 252.2+ KB

In [ ]:
df["mes"].unique()

array(['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho',
       'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
      dtype=object)

In [ ]:
df["estado"].unique()

array(['Acre', 'alagoas', 'Amapa', 'Amazonas', 'Bahia', 'Ceara',
       'Distrito Federal', 'Espirito Santo', 'Goias', 'Maranhao',
       'Mato Grosso', 'Minas Gerais', 'pará', 'Paraiba', 'Pernambuco',
       'Piau', 'Rio', 'rondonia', 'Roraima', 'Santa Catarina',
       'Sao Paulo', 'Sergipe', 'Tocantins'], dtype=object)

In [ ]:
df["numero"].unique()

array(['0 Fires', '10 Fires', '12 Fires', ..., '2.032', '833', '623'],
      dtype=object)

In [ ]:
df["encontro"].unique()

array(['1/1/1998', '1/1/1999', '1/1/2000', '1/1/2001', '1/1/2002',
       '1/1/2003', '1/1/2004', '1/1/2005', '1/1/2006', '1/1/2007',
       '1/1/2008', '1/1/2009', '1/1/2010', '1/1/2011', '1/1/2012',
       '1/1/2013', '1/1/2014', '1/1/2015', '1/1/2016', '1/1/2017'],
      dtype=object)

In [ ]:
#1)Renaming the columns
#dict={"old_col":"new_col"}
#syntax: df.rename(columns=dict,inplace=True)
d={"ano":"year",	"mes":"month","estado":"state",	"numero":"no_of_fires",	"encontro":"date"}
df.rename(columns=d,inplace=True)
df

      year     month      state no_of_fires      date
0     1998   Janeiro       Acre     0 Fires  1/1/1998
1     1999   Janeiro       Acre     0 Fires  1/1/1999
2     2000   Janeiro       Acre     0 Fires  1/1/2000
3     2001   Janeiro       Acre     0 Fires  1/1/2001
4     2002   Janeiro       Acre     0 Fires  1/1/2002
...    ...       ...        ...         ...       ...
6449  2012  Dezembro  Tocantins         128  1/1/2012
6450  2013  Dezembro  Tocantins          85  1/1/2013
6451  2014  Dezembro  Tocantins         223  1/1/2014
6452  2015  Dezembro  Tocantins         373  1/1/2015
6453  2016  Dezembro  Tocantins         119  1/1/2016

[6454 rows x 5 columns]

In [ ]:
#2)Dropping duplicate rows
#syntax: df.drop_duplicates(inplace=True)
df.drop_duplicates(inplace=True)
df.shape

(6424, 5)

In [ ]:
#3)Changing the data present inside columns
#syntax: d={"old_data":"new_data",....}
#df["col"]=df["col"].map(d)
#note: length of dictionary should be equal to unique values
d={"Janeiro":"jan", "Fevereiro":"feb", "Março":"march", "Abril":"april", "Maio":"may", "Junh":"june", "Julho":"july",
       "Agosto":"aug", "Setembro":"sep", "Outubro":"oct", "Novembro":"nov", "Dezembro":"dec"}
df["month"]=df["month"].map(d)
df["month"].unique()

array(['jan', 'feb', 'march', 'april', 'may', nan, 'july', 'aug', 'sep',
       'oct', 'nov', 'dec'], dtype=object)

In [ ]:
#4)Applying inbuilt functions on a column
#syntax:df[col]=df[col].str.fname(args)
df["month"]=df["month"].str.upper()
df["month"]=df["month"].str.capitalize()
df

      year month      state no_of_fires      date
0     1998   Jan       Acre     0 Fires  1/1/1998
1     1999   Jan       Acre     0 Fires  1/1/1999
2     2000   Jan       Acre     0 Fires  1/1/2000
3     2001   Jan       Acre     0 Fires  1/1/2001
4     2002   Jan       Acre     0 Fires  1/1/2002
...    ...   ...        ...         ...       ...
6449  2012   Dec  Tocantins         128  1/1/2012
6450  2013   Dec  Tocantins          85  1/1/2013
6451  2014   Dec  Tocantins         223  1/1/2014
6452  2015   Dec  Tocantins         373  1/1/2015
6453  2016   Dec  Tocantins         119  1/1/2016

[6424 rows x 5 columns]

In [ ]:
#5)Removing unwanted data
#df["col"]=df["col"].str.strip("unwanted data")
df["no_of_fires"]=df["no_of_fires"].str.strip(" Fires")
df
#here fires after the numeric value is removed

      year month      state no_of_fires      date
0     1998   Jan       Acre           0  1/1/1998
1     1999   Jan       Acre           0  1/1/1999
2     2000   Jan       Acre           0  1/1/2000
3     2001   Jan       Acre           0  1/1/2001
4     2002   Jan       Acre           0  1/1/2002
...    ...   ...        ...         ...       ...
6449  2012   Dec  Tocantins         128  1/1/2012
6450  2013   Dec  Tocantins          85  1/1/2013
6451  2014   Dec  Tocantins         223  1/1/2014
6452  2015   Dec  Tocantins         373  1/1/2015
6453  2016   Dec  Tocantins         119  1/1/2016

[6424 rows x 5 columns]

In [ ]:
#6)Handling missing values
df.dropna(inplace=True)
df.isnull().sum()

year           0
month          0
state          0
no_of_fires    0
date           0
dtype: int64

In [ ]:
#7)changing the datatype of columns
#df[col]=df[col].astype(dest_dtype)
df["no_of_fires"]=df["no_of_fires"].astype(float)
df["no_of_fires"]=df["no_of_fires"].astype(int)
df["no_of_fires"].unique()

array([  0,  10,  12,   4,   1,   3,   5,   2,  11,  19,   7,   6,   8,
         9,  21,  37,  39, 168,  42,  33,  29,  41,  31, 126,  93,  71,
        54,  60, 109, 533, 457, 130,  63, 136, 396, 728, 645, 839, 960,
       445, 194, 425, 739, 679, 509, 209, 265, 290,  44,  18, 137, 687,
       740, 461, 547, 316, 203, 652, 565, 292,  97, 348, 258, 406, 905,
        86,  15,  14,  74,  13,  79,  56,  46,  98,  58, 150,  83,  55,
       104,  23,  36,  49,  81,  24,  38,  20,  16,  28,  32,  26,  52,
        27,  35,  70,  34,  17,  25,  22,  30,  40,  95, 162,  76,  43,
        45,  50,  59, 155,  73,  88,  67, 112,  61, 128,  85, 192, 142,
       557, 355, 412, 335, 405, 395, 765, 304, 475, 385, 480, 827, 793,
       131, 157, 750, 949, 685, 207, 198, 266, 339, 282, 969, 341, 484,
       858,  84, 593, 200, 411, 123, 360, 422, 148, 354, 269, 491, 158,
        82,  53, 770,  65,  62,  92, 107, 275,  69,  64, 116, 140,  51,
       146, 180, 177, 676, 108, 199, 640, 271, 234, 248, 202, 356, 321,
       259, 501, 741, 861, 267, 216, 189, 166, 928, 911, 998, 479, 145,
       332, 695, 725, 710, 545, 721, 215, 632, 889, 694, 952, 244, 169,
       261,  90, 973, 399, 682, 220, 591, 552, 196, 147, 102, 121,  80,
       236, 293, 133, 114, 125, 439, 303, 225, 373, 314, 297, 101, 179,
       132, 256, 285, 154, 204, 223, 122, 143, 277, 113, 235, 117, 206,
       156, 231, 418, 100, 274, 115, 141, 135, 249, 404, 363, 229, 281,
       163, 110, 376,  89, 151, 103, 149, 183, 190,  94, 106, 124, 120,
       161, 326, 224, 144, 219, 310, 811, 519, 578, 906, 362, 345, 300,
       815, 453, 633, 979, 948, 995, 611, 610, 674, 829, 724, 699, 239,
       402, 605, 288, 408, 174, 848, 423, 308, 226, 230, 477, 164,  47,
       264, 384, 211, 347, 273,  91,  75, 111, 182, 278, 127, 590, 801,
       172, 185, 237, 241, 357, 609, 214, 370, 505, 309, 875, 581, 964,
       816, 435, 502, 415, 466, 517, 658, 575, 524, 669, 812, 276, 397,
       389, 631, 956, 643, 819,  48, 159,  99,  72,  66, 118,  96, 152,
        77, 105, 134, 186, 232, 318, 407, 625, 467, 336, 446, 707, 462,
       559, 769, 959, 901, 528, 616, 417, 914, 892, 246, 153, 398, 295,
        57, 702, 391, 759, 511, 175, 459, 379, 713, 416, 755, 530, 617,
       233, 450, 188, 208, 644, 626, 704, 197, 252, 279, 129,  68, 436,
       221, 428, 319, 195, 494, 187,  78, 119, 286, 549, 512, 972, 895,
       800, 896, 301, 438, 947, 476, 245, 527, 298, 171, 315, 374, 482,
       592, 272, 871, 383, 213, 431, 193, 375, 542, 337, 554, 743, 448,
       325, 563, 655, 705, 719, 641, 903, 441, 372, 521, 338, 859, 606,
       731, 942, 359, 516, 933, 541, 845, 842, 299, 588, 768, 918, 813,
       846, 492, 447, 201, 139, 165, 170, 291, 328, 927, 160, 935, 529,
       289, 589, 250, 538, 371, 228, 953, 456, 677, 510, 365, 576, 657,
       647, 668, 432, 854, 597, 378, 507, 306, 380,  87, 577, 394, 579,
       403, 437, 392, 167, 251, 430, 181, 638, 426, 708, 772, 615, 971,
       661, 825, 766, 689, 684, 178, 381, 294, 238, 331, 280, 451, 351,
       270, 262, 504, 891, 938, 849, 342, 844, 580, 733, 522, 481, 646,
       651, 987, 878, 386, 866, 413, 913, 443, 599, 452, 666, 327, 424,
       503, 388, 138, 254, 243, 560, 465, 486, 831, 352, 191, 364, 176,
       334, 534, 564, 919, 302, 864, 361, 690, 754, 711, 499, 943, 790,
       872, 939, 594, 717, 897, 449, 788, 317, 329, 570, 468, 346, 184,
       205, 353, 313, 500, 366, 212, 222, 284, 865, 885, 824, 642, 410,
       414, 828, 444, 573, 628, 343, 680, 227, 539, 798, 747, 483, 796,
       822, 555, 526, 253, 401, 217, 330, 767, 283, 820, 665, 268, 312,
       307, 596, 600, 802, 915, 595, 934, 794, 572, 470, 497, 797, 981,
       525, 582, 977, 809, 495, 882, 368, 490, 434, 763, 260, 887, 488,
       419, 369, 350, 618, 778, 830, 976, 762, 982, 989, 718, 833, 623])

In [ ]:
#8)Dropping unwanted columns
#df=df.drop([col1,col2,col3,....],axis=1)
df=df.drop(["state"],axis=1)
df

      year month  no_of_fires      date
0     1998   Jan            0  1/1/1998
1     1999   Jan            0  1/1/1999
2     2000   Jan            0  1/1/2000
3     2001   Jan            0  1/1/2001
4     2002   Jan            0  1/1/2002
...    ...   ...          ...       ...
6449  2012   Dec          128  1/1/2012
6450  2013   Dec           85  1/1/2013
6451  2014   Dec          223  1/1/2014
6452  2015   Dec          373  1/1/2015
6453  2016   Dec          119  1/1/2016

[5760 rows x 4 columns]

In [ ]:
#dropping unwanted rows
#df=df.drop([ind1,ind2])  #axis no need bcoz this is row wise operation
df=df.drop([0,1,2])
df

      year month  no_of_fires      date
3     2001   Jan            0  1/1/2001
4     2002   Jan            0  1/1/2002
5     2003   Jan           10  1/1/2003
6     2004   Jan            0  1/1/2004
7     2005   Jan           12  1/1/2005
...    ...   ...          ...       ...
6449  2012   Dec          128  1/1/2012
6450  2013   Dec           85  1/1/2013
6451  2014   Dec          223  1/1/2014
6452  2015   Dec          373  1/1/2015
6453  2016   Dec          119  1/1/2016

[5757 rows x 4 columns]

In [ ]:
#10)Resetting index
#df.reset_index(inplace=True)
df.reset_index(inplace=True)      #now index column is unwanted
df=df.drop("index",axis=1)
df

      year month  no_of_fires      date
0     2001   Jan            0  1/1/2001
1     2002   Jan            0  1/1/2002
2     2003   Jan           10  1/1/2003
3     2004   Jan            0  1/1/2004
4     2005   Jan           12  1/1/2005
...    ...   ...          ...       ...
5752  2012   Dec          128  1/1/2012
5753  2013   Dec           85  1/1/2013
5754  2014   Dec          223  1/1/2014
5755  2015   Dec          373  1/1/2015
5756  2016   Dec          119  1/1/2016

[5757 rows x 4 columns]

In [ ]:
#11)changing the specific data
#df[col]=df[col].str.replace("old","new")

In [ ]:
#Data Cleaning task
df=pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/laptopData.csv",encoding="ISO-8859-1")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1273 non-null   float64
 1   Company           1273 non-null   object
 2   TypeName          1273 non-null   object
 3   Inches            1273 non-null   object
 4   ScreenResolution  1273 non-null   object
 5   Cpu               1273 non-null   object
 6   Ram               1273 non-null   object
 7   Memory            1273 non-null   object
 8   Gpu               1273 non-null   object
 9   OpSys             1273 non-null   object
 10  Weight            1273 non-null   object
 11  Price             1273 non-null   float64
dtypes: float64(2), object(10)
memory usage: 122.3+ KB

In [ ]:
df.isnull().sum()

Unnamed: 0          30
Company             30
TypeName            30
Inches              30
ScreenResolution    30
Cpu                 30
Ram                 30
Memory              30
Gpu                 30
OpSys               30
Weight              30
Price               30
dtype: int64

In [ ]:
#Handling null values
df.dropna(inplace=True)
df.isnull().sum()

Unnamed: 0          0
Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price               0
dtype: int64

In [ ]:
#remove unnamed
df=df.drop("Unnamed: 0",axis=1)
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [ ]:
#drop duplicate rows
df.drop_duplicates(inplace=True)
df.shape

(1244, 11)

In [ ]:
df["Company"].unique()

array(['Apple', 'HP', 'Acer', 'Asus', 'Dell', 'Lenovo', 'Chuwi', 'MSI',
       'Microsoft', 'Toshiba', 'Huawei', 'Xiaomi', 'Vero', 'Razer',
       'Mediacom', 'Samsung', 'Google', 'Fujitsu', 'LG'], dtype=object)

In [ ]:
df["TypeName"].unique()

array(['Ultrabook', 'Notebook', 'Gaming', '2 in 1 Convertible',
       'Workstation', 'Netbook'], dtype=object)

In [ ]:
df["Inches"].unique()

array(['13.3', '15.6', '15.4', '14', '12', '17.3', '13.5', '12.5', '13',
       '18.4', '13.9', '11.6', '25.6', '35.6', '12.3', '27.3', '24',
       '33.5', '?', '31.6', '17', '15', '14.1', '11.3', '10.1'],
      dtype=object)

In [ ]:
#replacing question mark wirh zero and then with avg value
df["Inches"]=df["Inches"].replace("?","0")
df["Inches"]=df["Inches"].astype(float)
avg_inch=round(df["Inches"].mean())
avg_inch
df["Inches"]=df["Inches"].replace(0.0,avg_inch)
df["Inches"].unique()

array([13.3, 15.6, 15.4, 14. , 12. , 17.3, 13.5, 12.5, 13. , 18.4, 13.9,
       11.6, 25.6, 35.6, 12.3, 27.3, 24. , 33.5, 15. , 31.6, 17. , 14.1,
       11.3, 10.1])

In [ ]:
df["Ram"].unique()

array(['8GB', '16GB', '4GB', '2GB', '12GB', '64GB', '6GB', '32GB', '24GB',
       '1GB'], dtype=object)

In [ ]:
df["Memory"].unique()

array(['128GB SSD', '128GB Flash Storage', '256GB SSD', '512GB SSD',
       '500GB HDD', '256GB Flash Storage', '1TB HDD',
       '128GB SSD +  1TB HDD', '256GB SSD +  256GB SSD',
       '64GB Flash Storage', '32GB Flash Storage', '256GB SSD +  1TB HDD',
       '256GB SSD +  2TB HDD', '32GB SSD', '2TB HDD', '64GB SSD',
       '1.0TB Hybrid', '512GB SSD +  1TB HDD', '1TB SSD',
       '256GB SSD +  500GB HDD', '128GB SSD +  2TB HDD',
       '512GB SSD +  512GB SSD', '16GB SSD', '16GB Flash Storage',
       '512GB SSD +  256GB SSD', '512GB SSD +  2TB HDD',
       '64GB Flash Storage +  1TB HDD', '180GB SSD', '1TB HDD +  1TB HDD',
       '32GB HDD', '1TB SSD +  1TB HDD', '?', '512GB Flash Storage',
       '128GB HDD', '240GB SSD', '8GB SSD', '508GB Hybrid', '1.0TB HDD',
       '512GB SSD +  1.0TB Hybrid', '256GB SSD +  1.0TB Hybrid'],
      dtype=object)

In [ ]:
#we need to replace question mark with most repeated one
df["Memory"].mode()
df["Memory"]=df["Memory"].replace("?","256GB SSD")
df["Memory"].unique()

array(['128GB SSD', '128GB Flash Storage', '256GB SSD', '512GB SSD',
       '500GB HDD', '256GB Flash Storage', '1TB HDD',
       '128GB SSD +  1TB HDD', '256GB SSD +  256GB SSD',
       '64GB Flash Storage', '32GB Flash Storage', '256GB SSD +  1TB HDD',
       '256GB SSD +  2TB HDD', '32GB SSD', '2TB HDD', '64GB SSD',
       '1.0TB Hybrid', '512GB SSD +  1TB HDD', '1TB SSD',
       '256GB SSD +  500GB HDD', '128GB SSD +  2TB HDD',
       '512GB SSD +  512GB SSD', '16GB SSD', '16GB Flash Storage',
       '512GB SSD +  256GB SSD', '512GB SSD +  2TB HDD',
       '64GB Flash Storage +  1TB HDD', '180GB SSD', '1TB HDD +  1TB HDD',
       '32GB HDD', '1TB SSD +  1TB HDD', '512GB Flash Storage',
       '128GB HDD', '240GB SSD', '8GB SSD', '508GB Hybrid', '1.0TB HDD',
       '512GB SSD +  1.0TB Hybrid', '256GB SSD +  1.0TB Hybrid'],
      dtype=object)

In [ ]:
df["Weight"].unique()

array(['1.37kg', '1.34kg', '1.86kg', '1.83kg', '2.1kg', '2.04kg', '1.3kg',
       '1.6kg', '2.2kg', '0.92kg', '1.22kg', '2.5kg', '1.62kg', '1.91kg',
       '2.3kg', '1.35kg', '1.88kg', '1.89kg', '1.65kg', '2.71kg', '1.2kg',
       '1.44kg', '2.8kg', '2kg', '2.65kg', '2.77kg', '3.2kg', '1.49kg',
       '2.4kg', '2.13kg', '2.43kg', '1.7kg', '1.4kg', '1.8kg', '1.9kg',
       '3kg', '1.252kg', '2.7kg', '2.02kg', '1.63kg', '1.96kg', '1.21kg',
       '2.45kg', '1.25kg', '1.5kg', '2.62kg', '1.38kg', '1.58kg',
       '1.85kg', '1.23kg', '2.16kg', '2.36kg', '7.2kg', '2.05kg',
       '1.32kg', '1.75kg', '0.97kg', '2.56kg', '1.48kg', '1.74kg',
       '1.1kg', '1.56kg', '2.03kg', '1.05kg', '5.4kg', '4.4kg', '1.90kg',
       '1.29kg', '2.0kg', '1.95kg', '2.06kg', '1.12kg', '3.49kg',
       '3.35kg', '2.23kg', '?', '2.9kg', '4.42kg', '2.69kg', '2.37kg',
       '4.7kg', '3.6kg', '2.08kg', '4.3kg', '1.68kg', '1.41kg', '4.14kg',
       '2.18kg', '2.24kg', '2.67kg', '4.1kg', '2.14kg', '1.36kg',
       '2.25kg', '2.15kg', '2.19kg', '2.54kg', '3.42kg', '5.8kg',
       '1.28kg', '2.33kg', '1.45kg', '2.79kg', '8.23kg', '1.26kg',
       '1.84kg', '0.0002kg', '2.6kg', '2.26kg', '3.25kg', '1.59kg',
       '1.13kg', '1.42kg', '1.78kg', '1.10kg', '1.15kg', '1.27kg',
       '1.43kg', '2.31kg', '1.16kg', '1.64kg', '2.17kg', '1.47kg',
       '3.78kg', '1.79kg', '0.91kg', '1.99kg', '4.33kg', '1.93kg',
       '1.87kg', '2.63kg', '3.4kg', '3.14kg', '1.94kg', '1.24kg', '4.6kg',
       '4.5kg', '8.4kg', '2.73kg', '1.39kg', '2.29kg', '2.59kg', '2.94kg',
       '11.1kg', '1.14kg', '3.8kg', '6.2kg', '3.31kg', '1.09kg', '3.21kg',
       '1.19kg', '1.98kg', '1.17kg', '4.36kg', '1.71kg', '2.32kg',
       '4.2kg', '1.55kg', '0.81kg', '1.18kg', '2.72kg', '1.31kg',
       '0.920kg', '3.74kg', '1.76kg', '1.54kg', '2.83kg', '2.07kg',
       '2.38kg', '3.58kg', '1.08kg', '2.20kg', '0.98kg', '2.75kg',
       '1.70kg', '2.99kg', '1.11kg', '2.09kg', '4kg', '3.0kg', '0.99kg',
       '0.69kg', '3.52kg', '2.591kg', '2.21kg', '3.3kg', '2.191kg',
       '2.34kg', '4.0kg'], dtype=object)

In [ ]:
#Handling weight
df["Weight"]=df["Weight"].str.strip("kg")
df["Weight"].unique()
df["Weight"]=df["Weight"].replace("?","0")
df["Weight"]=df["Weight"].astype(float)
df["Weight"].mean()
df["Weight"]=df["Weight"].replace(0.0,2.0785)
df["Weight"].unique()

array([1.3700e+00, 1.3400e+00, 1.8600e+00, 1.8300e+00, 2.1000e+00,
       2.0400e+00, 1.3000e+00, 1.6000e+00, 2.2000e+00, 9.2000e-01,
       1.2200e+00, 2.5000e+00, 1.6200e+00, 1.9100e+00, 2.3000e+00,
       1.3500e+00, 1.8800e+00, 1.8900e+00, 1.6500e+00, 2.7100e+00,
       1.2000e+00, 1.4400e+00, 2.8000e+00, 2.0000e+00, 2.6500e+00,
       2.7700e+00, 3.2000e+00, 1.4900e+00, 2.4000e+00, 2.1300e+00,
       2.4300e+00, 1.7000e+00, 1.4000e+00, 1.8000e+00, 1.9000e+00,
       3.0000e+00, 1.2520e+00, 2.7000e+00, 2.0200e+00, 1.6300e+00,
       1.9600e+00, 1.2100e+00, 2.4500e+00, 1.2500e+00, 1.5000e+00,
       2.6200e+00, 1.3800e+00, 1.5800e+00, 1.8500e+00, 1.2300e+00,
       2.1600e+00, 2.3600e+00, 7.2000e+00, 2.0500e+00, 1.3200e+00,
       1.7500e+00, 9.7000e-01, 2.5600e+00, 1.4800e+00, 1.7400e+00,
       1.1000e+00, 1.5600e+00, 2.0300e+00, 1.0500e+00, 5.4000e+00,
       4.4000e+00, 1.2900e+00, 1.9500e+00, 2.0600e+00, 1.1200e+00,
       3.4900e+00, 3.3500e+00, 2.2300e+00, 2.0785e+00, 2.9000e+00,
       4.4200e+00, 2.6900e+00, 2.3700e+00, 4.7000e+00, 3.6000e+00,
       2.0800e+00, 4.3000e+00, 1.6800e+00, 1.4100e+00, 4.1400e+00,
       2.1800e+00, 2.2400e+00, 2.6700e+00, 4.1000e+00, 2.1400e+00,
       1.3600e+00, 2.2500e+00, 2.1500e+00, 2.1900e+00, 2.5400e+00,
       3.4200e+00, 5.8000e+00, 1.2800e+00, 2.3300e+00, 1.4500e+00,
       2.7900e+00, 8.2300e+00, 1.2600e+00, 1.8400e+00, 2.0000e-04,
       2.6000e+00, 2.2600e+00, 3.2500e+00, 1.5900e+00, 1.1300e+00,
       1.4200e+00, 1.7800e+00, 1.1500e+00, 1.2700e+00, 1.4300e+00,
       2.3100e+00, 1.1600e+00, 1.6400e+00, 2.1700e+00, 1.4700e+00,
       3.7800e+00, 1.7900e+00, 9.1000e-01, 1.9900e+00, 4.3300e+00,
       1.9300e+00, 1.8700e+00, 2.6300e+00, 3.4000e+00, 3.1400e+00,
       1.9400e+00, 1.2400e+00, 4.6000e+00, 4.5000e+00, 8.4000e+00,
       2.7300e+00, 1.3900e+00, 2.2900e+00, 2.5900e+00, 2.9400e+00,
       1.1100e+01, 1.1400e+00, 3.8000e+00, 6.2000e+00, 3.3100e+00,
       1.0900e+00, 3.2100e+00, 1.1900e+00, 1.9800e+00, 1.1700e+00,
       4.3600e+00, 1.7100e+00, 2.3200e+00, 4.2000e+00, 1.5500e+00,
       8.1000e-01, 1.1800e+00, 2.7200e+00, 1.3100e+00, 3.7400e+00,
       1.7600e+00, 1.5400e+00, 2.8300e+00, 2.0700e+00, 2.3800e+00,
       3.5800e+00, 1.0800e+00, 9.8000e-01, 2.7500e+00, 2.9900e+00,
       1.1100e+00, 2.0900e+00, 4.0000e+00, 9.9000e-01, 6.9000e-01,
       3.5200e+00, 2.5910e+00, 2.2100e+00, 3.3000e+00, 2.1910e+00,
       2.3400e+00])

In [ ]:
df.reset_index(inplace=True)
df=df.drop("index",axis=1)
df

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...
1239,Asus,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,4GB,500GB HDD,Nvidia GeForce 920M,Windows 10,2.20,38378.6496
1240,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.80,33992.6400
1241,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.30,79866.7200
1242,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.50,12201.1200
1243,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19,40705.9200